// USER ACTIONS
export const LOADING_USER = "LOADING_USER";
export const FAILED_USER = "FAILED_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// USERS ACTIONS
export const LOADING_USERS = "LOADING_USERS";
export const FAILED_USERS = "FAILED_USERS";
export const FETCH_USERS = "FETCH_USERS";


// FILTER ACTIONS
export const LOADING_FILTERED_POSTS = "LOADING_FILTERED_POSTS";
export const FAILED_FILTERED_POSTS = "FAILED_FILTERED_POSTS";
export const FETCH_FILTERED_POSTS = "FETCH_FILTERED_POSTS";

// NUMERIC
export const BATCH_SIZE = 5;